
name: 'jQA Standard CI Build'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '11 12 * * *'
    
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Build only
        run: mvn --batch-mode --no-transfer-progress -DskipTests -Djqassistant.skip clean install
      - name: Unit Testing
        run: mvn --batch-mode --no-transfer-progress -Djqassistant.skip clean install
      - name: Integration Testing
        run: mvn --batch-mode --no-transfer-progress -Djqassistant.skip -P IT clean install
      - name: Full Build
        run: mvn --no-transfer-progress -P IT -Djqassistant.skip=false clean install
